services:
  web:
    image: louiscouture/polcompass:latest
    build: .
    container_name: polcompass_web
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://root:44144419c+h@db:5432/polcompass
      - LOCAL_MODE=true
  db:
    restart: always
    image: postgres:latest
    container_name: polcompass_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: polcompass
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 44144419c+h

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d polcompass"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
    db_data:
